### ISSUE TITLE
Could not find any runtimeconfig file ([appname].runtimeconfig.json in app folder nor dotnet.runtimeconfig.json in sdk folder)

### ISSUE THREAD

**Issue by Owe1n** [agracio/electron-edge-js#187]
# Error when building Electron app for Mac M3 with `electron-edge-js`

Hi guys,

I'm facing an error when building for Mac (Mac M3).

Here is the relevant code snippet:

```javascript
import { app, shell, BrowserWindow, ipcMain } from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import icon from '../../resources/icon.png?asset'
import edge from 'electron-edge-js'
import path from 'path'

// .NET function definition
// @ts-ignore - electron-edge-js types might be inaccurate here, runtime expects string directly
const helloWorld = edge.func(`
  async (input) => {
      return ".NET Welcomes " + input.ToString();
  }
`)

const dllPath = path.join(__dirname, '../../libs/TestLibrary/bin/Release/net8.0/TestLibrary.dll')
console.log(`DLL Path: ${dllPath}`)

const helloWorld2 = edge.func({
  assemblyFile: dllPath,
  typeName: 'TestLibrary.Class1',
  methodName: 'GetCurrentTime'
})

const helloWorld3 = edge.func({
  assemblyFile: dllPath,
  typeName: 'TestLibrary.Class1',
  methodName: 'SayHello'
})

console.log('helloWorld2', helloWorld2(null, true))
console.log('helloWorld3', helloWorld3(null, true))
```
This snippet work fine when running npm run dev. 

As soon as I try to build, the builded version is not working and I get this error : Could not find any runtimeconfig file ([appname].runtimeconfig.json in app folder nor dotnet.runtimeconfig.json in sdk folder)

**Comment by agracio** [comment]
Does that happen on the same dev mac or when you deploy it to another machine? 
What you mean by 'build' are you using electron-builder, electron-forge etc?

**Comment by Owe1n** [comment]
On the same machine. 
I installed the .NET SDK and still facing the same issue.

I use electron-builder. 

```yaml
appId: com.mecagent-app.app
productName: mecagent-app
directories:
  buildResources: build
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintcache,eslint.config.mjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
  
asarUnpack:
  - resources/**
  - libs/**
win:
  executableName: mecagent-app
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/

```
